### ISSUE TITLE
[Bug] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dmouraneto** [growthbook/growthbook-golang#30]
### Summary
When under high load, sometimes I get this error

```
goroutine 17 [running]:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x8e7b68]
/go/pkg/mod/github.com/growthbook/growthbook-golang@v0.1.9/growthbook.go:106 +0x25
github.com/growthbook/growthbook-golang.New.func1(0x0?)
/go/pkg/mod/github.com/growthbook/growthbook-golang@v0.1.9/feature_repository.go:92
github.com/growthbook/growthbook-golang.repoUnsubscribe(...)
/go/pkg/mod/github.com/growthbook/growthbook-golang@v0.1.9/feature_repository.go:432 +0x71
github.com/growthbook/growthbook-golang.(*refreshData).removeSubscription(0x131d3c0, 0xc000f30628)
/go/pkg/mod/github.com/growthbook/growthbook-golang@v0.1.9/feature_repository.go:593
github.com/growthbook/growthbook-golang.getKey(...)
/go/pkg/mod/github.com/growthbook/growthbook-golang@v0.1.9/growthbook.go:519 +0x88
github.com/growthbook/growthbook-golang.(*GrowthBook).GetAPIInfo(0xc000f30628)
```

Here is the library code where the panic is generated:

```
func (gb *GrowthBook) GetAPIInfo() (string, string) {
	gb.inner.RLock()
	defer gb.inner.RUnlock()

	apiHost := gb.inner.context.APIHost
	if apiHost == "" {
		apiHost = "https://cdn.growthbook.io"
	}

	return strings.TrimRight(apiHost, "/"), gb.inner.context.ClientKey
}
```

This code is invoked because of GrowthBook finalizer. 
Don't know if the GC can collect the `context` before running the finalizer code and is causing this issue. Not sure what else can turn the context to an invalid state.

#### Expected Behavior

Don't panic

#### Current Behavior

panic

**Comment by abs** [comment]
Hi @dmouraneto - any chance you'd be willing to give https://pkg.go.dev/github.com/growthbook/growthbook-golang@v0.2.0 a try to see if it resolves this issue?

**Comment by dmouraneto** [comment]
@abs not sure what I did back then but I'm not having the issue anymore.
I'll test this new version and report if I find any issue.

**Comment by mkurkov** [comment]
Closing this issue as it should be resolved in version 0.2.0. If the problem persists, please let us know.
