### ISSUE TITLE
[Bug] More defensive around nil context

### ISSUE THREAD

**Issue by tinahollygb** [growthbook/growthbook-golang#5]
### Summary

With the fix in https://github.com/growthbook/growthbook-golang/pull/4 we added the possibility that if the user passes an array when creating context that the context can result in a nil value.

This can result in a nil pointer exception when they go to use it:

```
2023/04/20 13:12:32 http: panic serving [::1]:57747: runtime error: invalid memory address or nil pointer dereference
goroutine 20 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1854 +0xbf
panic({0x12c00c0, 0x15346c0})
	/usr/local/go/src/runtime/panic.go:890 +0x263
github.com/growthbook/growthbook-golang.(*GrowthBook).Feature(0x0, {0x130c438, 0xb})
	/Users/tina/go/pkg/mod/github.com/growthbook/growthbook-golang@v0.1.1/growthbook.go:104 +0x41
main.acmeHandler({0x1389440, 0xc00010a000}, 0xffffffffffffffff?)
	/Users/tina/Documents/code/growthbook/examples/go-example/acme_handler.go:61 +0x5e6
```

This can be reproduced in the [Go example](https://github.com/growthbook/examples/tree/main/go-example) when changing line 28 from:

```go
"dietaryRestrictions": []string{"gluten_free"},
```

To:

```go
"dietaryRestrictions": [1]string{"gluten_free"},
```

#### Expected Behavior

We do not want to crash the customers' apps when they provide invalid attributes. Ideally we can present a way for them to capture this and fall back to the default value.

One approach, instead of this being the API for creating a context:

```go
	context := growthbook.NewContext().
		WithFeatures(features).
		WithAttributes(userAttributes).
		WithTrackingCallback(trackingCallback)
```

We could change it to something like this:

```go
	context, err := growthbook.NewContext().
		WithFeatures(features).
		WithAttributes(userAttributes).
		WithTrackingCallback(trackingCallback)
```

This will allow the developer to check for an error and they can rely on the lack of error meaning it's safe to access `context`. 

As well, we may also want to be more defensive in the SDK itself. If a nil context is provided, perhaps we can create a basic context we can work with to prevent nil pointer exceptions.

Maybe both would be appropriate:

1. Returning error allows the developer to know something went wrong so they won't try to use the context. 
2. Being more defensive allows us to fall back to the default value in the case that they did do something wrong.

#### Current Behavior

The app will panic.

**Comment by tinahollygb** [comment]
Also, how hard would it be to support array types too?

**Comment by ian-ross** [comment]
I've made a change to allow the use of arrays and to generate a default (empty) context if a nil context value is passed to the `GrowthBook` constructor. None of the `With...` builder methods for `Context` generate anything that will lead to the `GrowthBook` constructor returning an invalid value now. I think that should cover most of the cases I can think of.

I am still assuming that _features_ will be decoded from JSON, or that if users construct them manually, they will use the right types. Otherwise, you end up having to thread code through everywhere to convert to the correct types, which is going to be messy.

I'm guessing that for normal users of this package, they will more or less always retrieve a JSON description of features from the GrowthBook API, rather than building them programmatically themselves. Is that right? If it is, I think it's OK to have the more sophisticated and unusual programmatic feature construction case to require the user to follow normal Go practices.

I do think it's a good idea to be more robust as far as types go for the attributes, since it's going to be normal for users to construct those themselves, and making people remember to write `[]interface{}` when they really want to write `[1]string` isn't good DX.
